baseURL: https://justinharrison.ca/
languageCode: en-us
title: Justin Harrison
theme: eureka

menus:
  main:
    - name: Home
      url: /
      weight: 1
    - name: Blog
      url: /posts/
      weight: 2
    - name: Resume
      url: /resume.pdf
      weight: 3

params:
  dateFormat: 2 January 2006
